### ISSUE TITLE
启动失败.

### ISSUE THREAD

**Issue by sukui** [youzan/nsq#8]
单机环境的时候启动失败
错误如下
```shell
root@iZbp12m3z176dptz83k3i2Z:/usr/local/nsq# ./bin/nsqlookupd -config=./etc/nsqlookupd.conf
Log file created at: [/usr/local/nsq/log /tmp]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa2c7fb]

goroutine 24 [running]:
github.com/absolute8511/xlock2.(*EtcdClient).Watch(0x0, 0xc4201c5c00, 0x1a, 0x0, 0x1, 0x0, 0x0)
	/Users/vincentlee/workspace/go/src/github.com/absolute8511/xlock2/etcd_client.go:121 +0x4b
github.com/youzan/nsq/consistence.(*NsqLookupdEtcdMgr).watchTopics(0xc42013db00)
	/Users/vincentlee/workspace/go/src/github.com/youzan/nsq/consistence/nsq_lookupd_etcd.go:376 +0x67
created by github.com/youzan/nsq/consistence.(*NsqLookupdEtcdMgr).InitClusterID
	/Users/vincentlee/workspace/go/src/github.com/youzan/nsq/consistence/nsq_lookupd_etcd.go:86 +0x127
```
配置文件:
```shell
## <addr>:<port> to listen on for TCP clients
tcp_address = "0.0.0.0:4160"

## <addr>:<port> to listen on for HTTP clients
http_address = "0.0.0.0:4161"

## rpc port used for cluster communication
rpc_port = "4260"
## address that will be registered with lookupd (defaults to the OS hostname)
#broadcast_address = ""
## the network interface for broadcast, the ip will be detected automatically.
# use this configure instead of broadcast_address to keep all the configure is the same 
broadcast_interface = "eth0"

## local reverse proxy port, basically used for collecting the stats 
# reverse_proxy_port = "4163"

cluster_id = "test-nsq"
## the etcd cluster ip list
cluster_leadership_addresses = "127.0.0.1:2379"

## duration of time a producer will remain in the active list since its last ping
inactive_producer_timeout = "100s"
# should at least twice as the ping interval on nsqd
nsqd_ping_timeout= "15s"

## duration of time a producer will remain tombstoned if registration remains
tombstone_lifetime = "45s"

## the detail of the log, larger number means more details
log_level = 2

## if empty, use the default flag value in glog
log_dir = "/usr/local/nsq/log"

## the time period (in hour) that the balance is allowed.
balance_interval = ["4", "5"]

## allow return topic as writable while no any channel under the topic
allow_write_with_nochannels = true
```
貌似是读取etcd的时候发生错误.
但是我本地使用etcdctl 操作是可以的.
etcd的版本:3.2.9

**Comment by absolute8511** [comment]
改下这个配置看看, `cluster_leadership_addresses = "http://127.0.0.1:2379"`

**Comment by sukui** [comment]
确实如此.
